apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops-operator
  annotations:
    apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
    apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
    argocd.argoproj.io/skip-reconcile: 'true'
  labels:
    apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    path: applications/app-of-apps/
    repoURL: 'https://github.com/romerobu/argo-pull-mode.git'
    targetRevision: HEAD