apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    path: applications/app-set/
    repoURL: 'https://github.com/romerobu/argo-pull-mode.git'
    targetRevision: HEAD