apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-2
  namespace: openshift-gitops
  annotations:
    apps.open-cluster-management.io/ocm-managed-cluster: 'dev-1'
    apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
    argocd.argoproj.io/skip-reconcile: "true"
  labels:
    apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: applications/app/deployment-2/
    repoURL: 'https://github.com/romerobu/argo-pull-mode.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true