apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-2
  namespace: openshift-gitops-operator
  annotations:
    argocd.argoproj.io/skip-reconcile: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    path: applications/app/deployment-2/
    repoURL: 'https://github.com/romerobu/argo-pull-mode.git'
    targetRevision: HEAD